apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoom-info-scraper-refine-db
  namespace: zoom-info
  labels:
    app: zoom-info-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoom-info-scraper-refine-db
  template:
    metadata:
      labels:
        app: zoom-info-scraper-refine-db
    spec:
      containers:
        - name: zoom-info-scraper-refine-db
          image: ghcr.io/sandesh-solabannavar/zoominfo-scraper:99d1380
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          env:
            - name: METHOD
              value: refineInfotropy
            - name: LIMIT
              value: "500"
            - name: CONTINUE
              value: "true"
          envFrom:
            - secretRef:
                name: zoom-info-scraper-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
