apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoom-info-scraper-copy-company
  namespace: zoom-info
  labels:
    app: zoom-info-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoom-info-scraper-copy-company
  template:
    metadata:
      labels:
        app: zoom-info-scraper-copy-company
    spec:
      containers:
        - name: zoom-info-scraper-copy-company
          image: ghcr.io/sandesh-solabannavar/zoominfo-scraper:0ace033
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          env:
            - name: METHOD
              value: processCompanyCopy
            - name: LIMIT
              value: "200"
            - name: CONTINUE
              value: "true"
            - name: INDUSTRY
              value: "Customer Relationship Management (CRM) Software"
          envFrom:
            - secretRef:
                name: zoom-info-scraper-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
