apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoom-info-scraper-history-desc
  namespace: zoom-info
  labels:
    app: zoom-info-scraper-history-desc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoom-info-scraper-history-desc
  template:
    metadata:
      labels:
        app: zoom-info-scraper-history-desc
    spec:
      containers:
        - name: zoom-info-scraper-history-desc
          image: ghcr.io/sandesh-solabannavar/zoominfo-scraper:99d1380
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          env:
            - name: COUNTRY
              value: US
            - name: METHOD
              value: processEmploymentHistoryCompaniesData
            - name: ORDER
              value: desc
            - name: LIMIT
              value: "500"
          envFrom:
            - secretRef:
                name: zoom-info-scraper-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
