apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoom-info-scraper-company-update
  namespace: zoom-info
  labels:
    app: zoom-info-scraper-company-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoom-info-scraper-company-update
  template:
    metadata:
      labels:
        app: zoom-info-scraper-company-update
    spec:
      containers:
        - name: zoom-info-scraper-company-update
          image: ghcr.io/sandesh-solabannavar/zoominfo-scraper:ebf6d36
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          env:
            - name: COUNTRY
              value: US
            - name: METHOD
              value: refreshCompanies
            - name: ORDER
              value: asc
            - name: LIMIT
              value: "500"
          envFrom:
            - secretRef:
                name: zoom-info-scraper-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
