apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoom-info-scraper-gb
  namespace: zoom-info
  labels:
    app: zoom-info-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoom-info-scraper-gb
  template:
    metadata:
      labels:
        app: zoom-info-scraper-gb
    spec:
      containers:
        - name: zoom-info-scraper-gb
          image: ghcr.io/sandesh-solabannavar/zoominfo-scraper:53a35bc
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          env:
            - name: COUNTRY
              value: GB
            - name: METHOD
              value: main
            - name: ORDER
              value: asc
            - name: LIMIT
              value: "100"
          envFrom:
            - secretRef:
                name: zoom-info-scraper-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
