apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoom-info-scraper-industry
  namespace: zoom-info
  labels:
    app: zoom-info-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoom-info-scraper-industry
  template:
    metadata:
      labels:
        app: zoom-info-scraper-industry
    spec:
      containers:
        - name: zoom-info-scraper-industry
          image: ghcr.io/sandesh-solabannavar/zoominfo-scraper:1c06556
          imagePullPolicy: IfNotPresent # Important for using remote images
          ports:
            - containerPort: 3000
          env:
            - name: INDUSTRY
              value: software.crm
            - name: METHOD
              value: scrapeByIndustryLocation
            - name: STATE
              value: "Canada - All"
          envFrom:
            - secretRef:
                name: zoom-info-scraper-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
