apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment-history.yaml
  - deployment-company-update.yaml
  - deployment.yaml
  - deployment-refine-db.yaml
  # - deployment-company-update-desc.yaml
  # - deployment-copy.yaml
  # - deployment-copy-company.yaml

  # - deployment-industry-scraping.yaml
  # - postgres.yaml
  # - deployment-reverse.yaml
  # - deployment-gb.yaml
  # - deployment-canada.yaml
  # - deployment-germany.yaml
  # - deployment-history-desc.yaml
