apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: plane
    repo: https://helm.plane.so/
    releaseName: plane
    namespace: plane
    version: 1.49.0
    valuesFile: values.yaml
