apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: plane-ce
    repo: https://helm.plane.so/
    releaseName: plane
    namespace: plane
    valuesFile: values.yaml
