ingress:
  enabled: true
  appHost: plane.isandeshsol.com
  ingressClassName: traefik
  ingress_annotations:
    cert-manager.io/cluster-issuer: letsencrypt-stg
    cert-manager.io/common-name: plane.isandeshsol.com
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

external_secrets:
  app_env_existingSecret: plane-secret

redis:
  storageClass: longhorn

postgres:
  storageClass: longhorn
  volumeSize: 10Gi

rabbitmq:
  storageClass: longhorn

minio:
  storageClass: longhorn